### ISSUE TITLE
inccompatible with iOS 14?

### ISSUE THREAD

**Issue by Droppix** [malekwasim/WMSegmentControl#10]
Hi,

I tested in the simulator (iOS 14), but the program blocked (run loop, pb with layoutSubviews / updateView)

**Comment by malekwasim** [comment]
Thanks for bringing this to notice, i will check and update.

**Comment by NasrullahKhan** [comment]
Hi.. please fix this issue asap i have to release the build to client within 24 hours. complete UI blocked.

**Comment by chaitanyakonduru** [comment]
I have removed updateview() from layoutsubviews() in WMSegmentControl class  and renamed the SelectedFont to selectedFont and it is working fine in iOS14

**Comment by malekwasim** [comment]
Thanks @chaitanyakonduru . i will update the code this weekend @NasrullahKhan @Droppix Please use the solution of as mention by @chaitanyakonduru. sorry for the inconvenience.

**Comment by akovalov** [comment]
@malekwasim here is a quick fix https://github.com/malekwasim/WMSegmentControl/pull/11

**Comment by malekwasim** [comment]
pod has been updated. Thank you all for your support.
