### ISSUE TITLE
Initializing from the code will still cause a memory issue in iOS14.

### ISSUE THREAD

**Issue by fathy000** [malekwasim/WMSegmentControl#12]
I'm initializing and adding it to the view in viewDidLoad as follows.
```
private lazy var segmentControll: WMSegment = {
        let segmentControll = WMSegment()
        segmentControll.colors = [.gray, .red, .blue]
        segmentControll.type = SegementType.onlyImage
        segmentControll.bottomBarHeight = 2
        segmentControll.translatesAutoresizingMaskIntoConstraints = false
        segmentControll.selectorType = SelectorType.bottomBar
        segmentControll.textColor = .red
        segmentControll.selectorColor = .gray
        segmentControll.selectorTextColor = .gray
        segmentControll.buttonImages = "pen,pen,pen"
        segmentControll.addTarget(self, action: #selector(colorSegmentControllValueChanged(sender:)), for: .valueChanged)
        return segmentControll
    }()
```

**Comment by malekwasim** [comment]
There was still an issue with iOS 14 as layoutsubviews are calling multiple time, now i have tested the issues and resolved and you will be able to use the control. please make sure you have version 2.1 of WMSegmentControl on cocoapods. please check the example if you want to support device rotation as there is bit extra code you will need in appdelegate.

Thanks alot for reporting issue. please let me know if this solution works for you or not.

**Comment by fathy000** [comment]
Thank you for your quick response.
I've confirmed that it's version 2.1, but it's still happening!

**Comment by fathy000** [comment]
I'm really sorry.
I was wrong in checking.

I could see the improvement.
Thank you.
