### ISSUE TITLE
Animation for button selection not working properly

### ISSUE THREAD

**Issue by Pavan96** [malekwasim/WMSegmentControl#13]
When we select second button slide animation working properly but once we select first button it will not animate it just select that button. Any idea or suggestion will be helpful.

**Comment by malekwasim** [comment]
Thank you for reporting, i will look into it and update here

**Comment by harifsp** [comment]
Any Solution? Still facing the improper animation effect.(like while selecting the 3rd segment button, animation effects begins from the first) 
Please fix this issue!

**Comment by kirti301290** [comment]
@malekwasim @Pavan96 @harifsp 
Please let me know do you find any solution  for this animation problem
Thanks

**Comment by malekwasim** [comment]
Hello all, 
I have not found any solution so far that works perfectly on iOS 14.
Still working on it
Thanks.

**Comment by chaitu7979** [comment]
> When we select second button slide animation working properly but once we select first button it will not animate it just select that button. Any idea or suggestion will be helpful.

Hello friends i got the solution for animation.

Please go through class  

    public var selectedSegmentIndex: Int = 0 {
         didSet {
             if oldValue != selectedSegmentIndex {
                 updateView()
             }
         }
     }

Change Like This 

 public var selectedSegmentIndex: Int = 0

it will work for me. i think it will helpful for you

**Comment by malekwasim** [comment]
Thank you very much @chaitu7979.
 i will test it out in iOS 14 and will update you

**Comment by malekwasim** [comment]
I have publish a new version (2.2) with resolved animation issue thanks to @chaitu7979.
Please make sure you are using version 2.2 to get this update.

Thanks you for your effort and support.
