### ISSUE TITLE
Image of the first selection  is not appearing 

### ISSUE THREAD

**Issue by Fareeha-Naz** [malekwasim/WMSegmentControl#16]
Hi dear
  Image of the first selection  is not appearing, when first segment is selected

**Comment by malekwasim** [comment]
Hello,
I will check and update you.
Thanks for bringing this issue.

**Comment by malekwasim** [comment]
Hi @Fareeha-Naz 
The issue is resolve and you can use the WMSegment.swift code as of now to use it. 
I will publish new version of pod in some days.
Thanks.

**Comment by Fareeha-Naz** [comment]
ok fine thanks alot!!!!!

**Comment by malekwasim** [comment]
@Fareeha-Naz 
New version uploaded.
