### ISSUE TITLE
The 2nd image don't show

### ISSUE THREAD

**Issue by Tinh04** [malekwasim/WMSegmentControl#17]
Hi guy!
I have problem on 2nd image for segment.
If i don't set the button title, only show the first image.
Pls check it, thanks a lot.

**Comment by Tinh04** [comment]
Hi guy!
I have problem on 2nd image for segment.
If i don't set the button title, only show the first image.
Pls check it for me, thanks a lot.

**Comment by malekwasim** [comment]
If you are using Pod then please try installing manually and use the WMSegment.swift file from latest commit. i will release pos in few days. if issue still persist let me know.
Thanks

**Comment by Tinh04** [comment]
I fixed it, thank you very much!
