### ISSUE TITLE
Does not fit more than ten options

### ISSUE THREAD

**Issue by krutitrivedi** [malekwasim/WMSegmentControl#3]
hello, i want to add more than 10 options but i whenever i tried to add it truncate middle can you please help me to figure-out this issue.

**Comment by malekwasim** [comment]
Hi,
I will check it out and update you.
Thank you.

**Comment by malekwasim** [comment]
Hi,
This control was created to replace the default segment control. So it
doesn't have the scroll option.

However if you want multiple options, you can use the collection view for
your purpose.

If you need any help please let me know.
Thank you.
