### ISSUE TITLE
for arabic 

### ISSUE THREAD

**Issue by farazhaider88** [malekwasim/WMSegmentControl#4]
for arabic case what changes need to be done ?

**Comment by malekwasim** [comment]
yourSegment.buttonTitles = "سعادة,مرحبا,يبتسم"

and you are good to go.
![Screenshot 2020-04-08 at 2 06 58 PM](https://user-images.githubusercontent.com/28384717/78762993-3e977e80-79a2-11ea-8b5e-c7e88bbeb3ef.png)

let me know if are still facing issues
