### ISSUE TITLE
PDF images support

### ISSUE THREAD

**Issue by sanket2126** [malekwasim/WMSegmentControl#5]
Using PDF image when normal type is used.
It does not display properly  and text are not visible
Check this fiirst image is PDF and second is png

<img width="259" alt="Screenshot 2020-04-10 at 12 04 42 PM" src="https://user-images.githubusercontent.com/35295662/78968972-7843c300-7b23-11ea-96de-a82688bf1515.png">

**Comment by malekwasim** [comment]
Hi Sanket, 
with release of version 1.0 , you can find example of PDF image.
with pdf icon just make sure the icon scale is selected to single scale and it will work fine
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-26 at 20 02 26](https://user-images.githubusercontent.com/28384717/88483247-40527580-cf84-11ea-97d6-f460947a3cdf.png)
![Screenshot 2020-07-26 at 8 02 54 PM](https://user-images.githubusercontent.com/28384717/88483255-5102eb80-cf84-11ea-8e49-f0be695c94f0.png)

Thanks
