### ISSUE TITLE
Check when Segment is pressed

### ISSUE THREAD

**Issue by derens99** [malekwasim/WMSegmentControl#6]
Hello, so I see when the segmented control is pressed by the two examples you gave, but where do you implement the callback function? I currently have it inside my class, but that's working. I'm looking to have a way to signal whenever a different segment is pressed.

Thanks

**Comment by malekwasim** [comment]
Hello, As you already know you get selected segment index by two ways. If i connect a WMSegment with IBOutlet i setup segment as following
//
```
@IBOutlet weak var segFormType: WMSegment!
 override func viewDidLoad() {
        super.viewDidLoad()
     
        setupSegment()
    }

private func setupSegment() {
        segFormType.buttonTitles = "apple,google"
        segFormType.normalFont = FONT_ROBOTO(20)
        segFormType.SelectedFont = FONT_ROBOTO_BOLD(20)
        
        segFormType.onValueChanged = { index in
            print(index)
        }
    }

```
//
If you don't connect the segment with IBOulet, you can use the @IBAction function as describe in description.

If this doesn't help you, please provide the code you are using

Thanks.

**Comment by derens99** [comment]
Great worked perfectly! Thanks.
