### ISSUE TITLE
Stuck at Indexing

### ISSUE THREAD

**Issue by adrianseraspi12** [malekwasim/WMSegmentControl#9]
Every time I add the WMSegment in the storyboard, the Xcode will perform indexing and will not respond. I tried to remove the WMSegment and Xcode stops getting stuck at indexing

**Comment by malekwasim** [comment]
can you please provide more information like what xcode version you are using and swift version?

**Comment by adrianseraspi12** [comment]
Xcode version: 11.4.1
Swift version: 5

**Comment by malekwasim** [comment]
There are some issues with Xcode 11.3.1 and 11.4.1.
you can try adding the segment manually. or please test on different version of Xcode

**Comment by malekwasim** [comment]
I have experienced the same issue today, so need to look into it, However i have install it manually and it was working fine. you  can use WMSegment file instead of pod and it will work fine.

Thanks for identifying this issue

**Comment by adrianseraspi12** [comment]
Okay @malekwasim . Hope you'll fix it

**Comment by malekwasim** [comment]
Hi, I have release the new version with some fixes. please let me know if issue still persist
Thanks
